apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: content-platform-secrets
  namespace: content-platform-vnext
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: content-platform-secrets
    creationPolicy: Owner
  data:
    - secretKey: NODE_ENV
      remoteRef:
        key: abdalaidrous/clients/content-platform/latest
        property: NODE_ENV

    - secretKey: APP_NAME
      remoteRef:
        key: abdalaidrous/clients/content-platform/latest
        property: APP_NAME

    - secretKey: PORT
      remoteRef:
        key: abdalaidrous/clients/content-platform/latest
        property: PORT

    - secretKey: DB_HOST
      remoteRef:
        key: abdalaidrous/clients/content-platform/latest
        property: DB_HOST

    - secretKey: DB_PORT
      remoteRef:
        key: abdalaidrous/clients/content-platform/latest
        property: DB_PORT

    - secretKey: DB_NAME
      remoteRef:
        key: abdalaidrous/clients/content-platform/latest
        property: DB_NAME

    - secretKey: DB_USER
      remoteRef:
        key: abdalaidrous/clients/content-platform/latest
        property: DB_USER

    - secretKey: DB_PASSWORD
      remoteRef:
        key: abdalaidrous/clients/content-platform/latest
        property: DB_PASSWORD

    - secretKey: JWT_SECRET
      remoteRef:
        key: abdalaidrous/clients/content-platform/latest
        property: JWT_SECRET

    - secretKey: JWT_EXPIRES_IN
      remoteRef:
        key: abdalaidrous/clients/content-platform/latest
        property: JWT_EXPIRES_IN