apiVersion: v1
kind: Service
metadata:
  name: content-platform-api-svc
  namespace: content-platform-vnext
spec:
  selector:
    app: content-platform-api-vnext
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  sessionAffinity: ClientIP
  type: ClusterIP
